name: Landing CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**"
      - ".github/workflows/**"
  push:
    branches: [ "main" ]
    paths:
      - "**"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: landing-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/goalixa-landing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (local) with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: goalixa-landing:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run container
        run: |
          docker run -d --rm -p 8080:80 --name goalixa-landing-ci goalixa-landing:ci

      - name: Smoke test (retry)
        run: |
          set -e
          for i in $(seq 1 20); do
            if curl -fsS http://localhost:8080/ >/dev/null; then
              echo "OK"
              exit 0
            fi
            sleep 1
          done
          echo "Failed to reach landing page"
          docker logs goalixa-landing-ci || true
          exit 1

      - name: Cleanup
        if: always()
        run: |
          docker rm -f goalixa-landing-ci 2>/dev/null || true

  build_and_push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
