name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t goalixa-landing:ci .

      - name: Run container
        run: docker run -d -p 8080:80 --name goalixa-landing-ci goalixa-landing:ci

      - name: Smoke test
        run: |
          for i in 1 2 3 4 5; do
            if curl -fsS http://localhost:8080/ >/dev/null; then
              exit 0
            fi
            sleep 1
          done
          echo "Failed to reach landing page"
          exit 1

      - name: Cleanup
        if: always()
        run: docker rm -f goalixa-landing-ci
