version: "3.8"

networks:
  goalixa_net:
    external: true

services:
  landing:
    image: ghcr.io/amirrezarezaie/goalixa-landing:latest
    networks: [goalixa_net]
    ports:
      - "8081:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
