apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "goalixa-landing.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "goalixa-landing.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "goalixa-landing.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: landing
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
